export const wineMegaMenuData = {
    theoLoai: [
        { label: "Rượu vang đỏ", slug: "ruou-vang-do", category_id: "ruou-vang-do" },
        { label: "Rượu vang trắng", slug: "ruou-vang-trang", category_id: "ruou-vang-trang" },
        { label: "Rượu vang sủi", slug: "ruou-vang-sui", category_id: "ruou-vang-sui" },
        { label: "Champagne", slug: "champagne", category_id: "champagne" },
    ],
    theoQuocGia: [
        { label: "Vang Pháp", slug: "vang-phap", category_id: "phap" },
        { label: "Vang Úc", slug: "vang-uc", category_id: "uc" },
        { label: "Vang Ý", slug: "vang-y", category_id: "y" },
        { label: "Vang Tây Ban Nha", slug: "vang-tay-ban-nha", category_id: "tay-ban-nha" },
        { label: "Vang Đức", slug: "vang-duc", category_id: "duc" },
        { label: "Vang Nga", slug: "vang-nga", category_id: "nga" },
    ],
    theoVung: [
        { label: "Saint-Émilion", slug: "saint-emilion", category_id: "saint-emilion" },
        { label: "Pomerol", slug: "pomerol", category_id: "pomerol" },
        { label: "Languedoc", slug: "languedoc", category_id: "languedoc" },
        { label: "Puglia", slug: "puglia", category_id: "puglia" },
        { label: "Veneto", slug: "veneto", category_id: "veneto" },
        { label: "Abruzzo", slug: "abruzzo", category_id: "abruzzo" },
        { label: "Crecchio", slug: "crecchio", category_id: "crecchio" },
        { label: "Tuscany", slug: "toscana", category_id: "toscana" },
        { label: "Salento", slug: "salento", category_id: "salento" },
        { label: "Sicily", slug: "sicilia", category_id: "sicilia" },
    ],
    theoGiongNho: [
        { label: "Cabernet Sauvignon", slug: "cabernet-sauvignon", category_id: "cabernet-sauvignon" },
        { label: "Merlot", slug: "merlot", category_id: "merlot" },
        { label: "Shiraz", slug: "shiraz", category_id: "shiraz" },
        { label: "Chardonnay", slug: "chardonnay", category_id: "chardonnay" },
        { label: "Garnacha", slug: "garnacha", category_id: "garnacha" },
        { label: "Malvasia", slug: "malvasia", category_id: "malvasia" },
        { label: "Montepulciano", slug: "montepulciano", category_id: "montepulciano" },
        { label: "Moscato", slug: "moscato", category_id: "moscato" },
        { label: "Negroamaro", slug: "negroamaro", category_id: "negroamaro" },
        { label: "Petit Verdot", slug: "petit-verdot", category_id: "petit-verdot" },
        { label: "Pinot Grigio", slug: "pinot-grigio", category_id: "pinot-grigio" },
        { label: "Primitivo", slug: "primitivo", category_id: "primitivo" },
        { label: "Riesling", slug: "riesling", category_id: "riesling" },
        { label: "Sangiovese", slug: "sangiovese", category_id: "sangiovese" },
        { label: "Tempranillo", slug: "tempranillo", category_id: "tempranillo" },
        { label: "Zinfandel", slug: "zinfandel", category_id: "zinfandel" },
    ],
};

export const sanPhamBanChay = [
    {
        name: 'The Macallan 25 Sherry Oak',
        price: '75.000.000₫',
        imageUrl: '/images/dt_world_whisky_banner.webp',
        href: '/san-pham/the-macallan-25-sherry-oak',
    },
    {
        name: 'Yamazaki 12 Năm',
        price: '7.900.000₫',
        imageUrl: '/images/banner/3.jpg',
        href: '/san-pham/yamazaki-12',
    },
    {
        name: 'Château Margaux 2015',
        price: '35.000.000₫',
        imageUrl: 'https://images.unsplash.com/photo-1621644894301-cd6b2eaca610?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxyZWQlMjB3aW5lfGVufDB8fHx8MTc2NzQ2MTQyNnww&ixlib=rb-4.1.0&q=80&w=1080',
        href: '/san-pham/chateau-margaux-2015',
    },
];
