

import { PlaceHolderImages } from './placeholder-images';
import type { FullProduct, Category, BlogPost, Testimonial } from './types';

const getImage = (id: string) => {
  const img = PlaceHolderImages.find((img) => img.id === id);
  if (!img) {
    throw new Error(`Image with id ${id} not found`);
  }
  return {
    url: img.imageUrl,
    path: '',
    imageHint: img.imageHint
  };
};

const genericTastingNotes = {
  brand: 'N/A',
  chillFiltered: 'N/A',
  region: 'N/A',
  caskType: 'N/A',
  nose: 'Hương thơm phức hợp của trái cây chín và gỗ sồi.',
  palate: 'Vị rượu đậm đà, cân bằng với một chút gia vị.',
  finish: 'Hậu vị kéo dài, ấm áp và êm dịu.',
  color: 'Màu vàng hổ phách.',
};

const genericProductDetails = {
    title: "Thông tin chi tiết về sản phẩm",
    paragraphs: [
        "Đây là một sản phẩm tinh túy, là kết quả của quá trình chưng cất và ủ rượu công phu. Nhà sản xuất đã lựa chọn những nguyên liệu tốt nhất và áp dụng những kỹ thuật truyền thống để tạo ra một loại rượu độc đáo.",
        "Quá trình trưởng thành trong thùng gỗ sồi đã mang lại cho sản phẩm này những lớp hương vị phức tạp, từ hương trái cây ban đầu đến những nốt hương gỗ và gia vị sâu lắng theo thời gian."
    ],
    details: [
        { label: "Tên Gọi", value: "Đang cập nhật" },
        { label: "Nhà Sản Xuất/Chưng Cất", value: "Đang cập nhật" },
        { label: "Quốc Gia", value: "Đang cập nhật" },
        { label: "Tuổi Rượu", value: "Đang cập nhật" },
        { label: "Loại Thùng Ủ", value: "Đang cập nhật" },
        { label: "Nồng Độ Cồn", value: "Đang cập nhật" },
        { label: "Dung Tích", value: "700 ml" }
    ],
    tastingNote: {
        nose: "Hương thơm phong phú với các nốt hương của trái cây, hoa và gia vị.",
        palate: "Vị rượu mượt mà, cấu trúc tốt và cân bằng hoàn hảo.",
        finish: "Hậu vị dài, đáng nhớ và để lại ấn tượng sâu sắc."
    },
    conclusion: "Đây là một chai rượu xuất sắc, phù hợp cho những dịp đặc biệt hoặc để làm phong phú thêm bộ sưu tập của bạn. Nó thể hiện rõ nét đặc trưng của vùng sản xuất và tay nghề của người làm rượu."
};


export const sampleWines: FullProduct[] = [
  {
    id: '1',
    nameVN: 'Château Margaux Premier Grand Cru Classé',
    slug: 'chateau-margaux-2015',
    price: 35000000,
    description: 'Một biểu tượng của Bordeaux, loại rượu này mang đến sự phức hợp đáng kinh ngạc với hương hoa violet, dâu đen và gỗ tuyết tùng.',
    image: getImage('prod-detail-1'),
    isFeatured: true,
    status: 'published',
    tags: ['wine'],
    attributes: [
        { label: 'Xuất xứ', value: 'Pháp' },
        { label: 'Loại', value: 'Vang Đỏ' },
        { label: 'Nồng độ', value: '13.5%' },
    ],
    createdAt: '2023-01-01',
  },
  {
    id: '2',
    nameVN: 'Domaine de la Romanée-Conti Montrachet Grand Cru',
    slug: 'drc-montrachet-2018',
    price: 95000000,
    description: 'Loại rượu vang trắng được săn lùng nhất thế giới, thể hiện sự cân bằng hoàn hảo giữa sự đậm đà, khoáng chất và độ chua.',
    image: getImage('prod-detail-2'),
    isFeatured: true,
    status: 'published',
    tags: ['wine', 'old-rare'],
    attributes: [
        { label: 'Xuất xứ', value: 'Pháp' },
        { label: 'Loại', value: 'Vang Trắng' },
        { label: 'Nồng độ', value: '14%' },
    ],
    createdAt: '2023-01-02',
  },
  {
    id: '3',
    nameVN: 'Whispering Angel Rosé',
    slug: 'whispering-angel-rose',
    price: 1200000,
    description: 'Loại vang hồng tinh tế từ Provence với hương thơm của dâu tây, đào và một chút hương hoa.',
    image: getImage('prod-detail-3'),
    isNew: true,
    status: 'published',
    tags: ['wine'],
    attributes: [
        { label: 'Xuất xứ', value: 'Pháp' },
        { label: 'Loại', value: 'Vang Hồng' },
        { label: 'Nồng độ', value: '13%' },
    ],
    createdAt: '2023-01-03',
  },
  {
    id: '4',
    nameVN: 'Krug Grande Cuvée Brut Champagne',
    slug: 'krug-grande-cuvee',
    price: 8500000,
    description: 'Một loại Champagne sang trọng với sự phức hợp của hương bánh mì nướng, các loại hạt và trái cây họ cam quýt.',
    image: getImage('prod-detail-1'),
    isFeatured: true,
    status: 'published',
    tags: ['wine'],
    attributes: [
        { label: 'Xuất xứ', value: 'Pháp' },
        { label: 'Loại', value: 'Vang Sủi' },
        { label: 'Nồng độ', value: '12.5%' },
    ],
    createdAt: '2023-01-04',
  },
  {
    id: '5',
    nameVN: 'Château d\'Yquem Sauternes',
    slug: 'chateau-dyquem-2011',
    price: 15000000,
    description: 'Vua của các loại rượu vang ngọt, với các lớp hương mật ong, mơ, và hạnh nhân.',
    image: getImage('prod-detail-2'),
    isNew: true,
    status: 'published',
    tags: ['wine', 'old-rare'],
    attributes: [
        { label: 'Xuất xứ', value: 'Pháp' },
        { label: 'Loại', value: 'Vang Tráng Miệng' },
        { label: 'Nồng độ', value: '14.5%' },
    ],
    createdAt: '2023-01-05',
  },
  {
    id: '6',
    nameVN: 'Penfolds Grange Bin 95',
    slug: 'penfolds-grange-2017',
    price: 22000000,
    description: 'Biểu tượng của Úc, một loại Shiraz đậm đà và mạnh mẽ với hương vị của mận, sô cô la và gia vị.',
    image: getImage('prod-detail-3'),
    isFeatured: true,
    status: 'published',
    tags: ['wine', 'world'],
    attributes: [
        { label: 'Xuất xứ', value: 'Úc' },
        { label: 'Loại', value: 'Vang Đỏ' },
        { label: 'Nồng độ', value: '14.5%' },
    ],
    createdAt: '2023-01-06',
  },
  {
    id: '7',
    nameVN: 'The Lakes Whiskymaker\'s Editions - TASTING SET',
    slug: 'the-lakes-tasting-set',
    price: 2500000,
    description: 'Bộ sản phẩm khám phá hương vị đa dạng từ nhà The Lakes, bao gồm các phiên bản giới hạn.',
    image: getImage('gift-set-tasting'),
    status: 'published',
    tags: ['tasting-set'],
    attributes: [
        { label: 'Xuất xứ', value: 'Anh' },
        { label: 'Loại', value: 'Tasting Set' },
        { label: 'Nồng độ', value: '46.6%' },
    ],
    createdAt: '2023-01-07',
  },
  {
    id: '8',
    nameVN: 'Bộ Quà Tặng Macallan',
    slug: 'the-lakes-gift-set',
    price: 4800000,
    description: 'Bộ quà tặng sang trọng từ The Lakes, lựa chọn hoàn hảo cho những dịp đặc biệt.',
    image: getImage('gift-set-lakes-tet'),
    status: 'published',
    tags: ['gift-set'],
    attributes: [
        { label: 'Xuất xứ', value: 'Anh' },
        { label: 'Loại', value: 'Gift Set' },
        { label: 'Nồng độ', value: '46.6%' },
    ],
    createdAt: '2023-01-08',
  },
  {
    id: '9',
    nameVN: 'Chai Hennessy V.S.O.P Khắc Tên',
    slug: 'engraved-hennessy-vsop',
    price: 3200000,
    description: 'Cá nhân hóa món quà của bạn với dịch vụ khắc tên tinh xảo trên chai Hennessy V.S.O.P nổi tiếng.',
    image: getImage('engraving-banner'),
    status: 'published',
    tags: ['engraving', 'spirits'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '40%' },
      { label: 'Loại thùng', value: 'Cognac Cask' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-09',
  },
  {
    id: '10',
    nameVN: 'Springbank 15 Năm',
    slug: 'springbank-15',
    price: 6800000,
    description: 'Một chai Campbeltown single malt cổ điển, phức hợp với hương sherry, trái cây sẫm màu và một chút khói than bùn.',
    image: getImage('prod-detail-1'),
    status: 'published',
    tags: ['scotch', 'campbeltown'],
    attributes: [
      { label: 'Xuất xứ', value: 'Campbeltown, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '46%' },
      { label: 'Tuổi rượu', value: '15 năm' },
      { label: 'Loại thùng', value: 'Sherry' },
      { label: 'Lọc lạnh', value: 'Không' }
    ],
    createdAt: '2023-01-10',
  },
  {
    id: '11',
    nameVN: 'Glen Scotia Victoriana',
    slug: 'glen-scotia-victoriana',
    price: 3500000,
    description: 'Lấy cảm hứng từ thời Victoria, loại whisky này mạnh mẽ và đậm đà, được ủ trong thùng gỗ sồi cháy kỹ.',
    image: getImage('prod-detail-2'),
    status: 'published',
    tags: ['scotch', 'campbeltown'],
    attributes: [
      { label: 'Xuất xứ', value: 'Campbeltown, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '54.2%' },
      { label: 'Tuổi rượu', value: '10 năm' },
      { label: 'Loại thùng', value: 'Bourbon' },
      { label: 'Lọc lạnh', value: 'Không' }
    ],
    createdAt: '2023-01-11',
  },
  {
    id: '12',
    nameVN: 'Yamazaki 12 Năm',
    slug: 'yamazaki-12',
    price: 7900000,
    description: 'Loại single malt tiên phong của Nhật Bản, tinh tế và phức hợp với hương trái cây nhiệt đới, gỗ đàn hương và trầm hương.',
    image: getImage('prod-detail-3'),
    status: 'published',
    tags: ['world', 'japan'],
    attributes: [
      { label: 'Xuất xứ', value: 'Nhật Bản' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '43%' },
      { label: 'Tuổi rượu', value: '12 năm' },
      { label: 'Loại thùng', value: 'Mizunara' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-12',
  },
  {
    id: '13',
    nameVN: 'The Lakes Whiskymaker\'s Reserve No.7',
    slug: 'lakes-reserve-no7',
    price: 4500000,
    description: 'Phiên bản thứ bảy trong sê-ri được đánh giá cao, một loại single malt đậm đà hương sherry, phức hợp và cân bằng.',
    image: getImage('hero-lakes'),
    status: 'published',
    tags: ['world', 'england'],
    attributes: [
      { label: 'Xuất xứ', value: 'Anh' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '52%' },
      { label: 'Loại thùng', value: 'Sherry' },
      { label: 'Lọc lạnh', value: 'Không' }
    ],
    createdAt: '2023-01-13',
  },
  {
    id: '14',
    nameVN: 'The Macallan 25 Sherry Oak',
    slug: 'the-macallan-25-sherry-oak',
    price: 75000000,
    description: 'Một loại single malt whisky quý hiếm và sang trọng, được ủ trong những thùng gỗ sồi Sherry Oloroso chọn lọc từ Jerez, Tây Ban Nha.',
    image: getImage('featured-macallan-25'),
    status: 'published',
    tags: ['old-rare', 'scotch', 'speyside'],
    attributes: [
      { label: 'Xuất xứ', value: 'Speyside, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '43%' },
      { label: 'Tuổi rượu', value: '25 năm' },
      { label: 'Loại thùng', value: 'Sherry' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-14',
  },
  {
    id: '15',
    nameVN: 'Glenfiddich 12 Năm',
    slug: 'glenfiddich-12',
    price: 1800000,
    description: 'Một trong những loại single malt bán chạy nhất thế giới, đặc trưng bởi hương lê tươi và gỗ sồi tinh tế.',
    image: getImage('prod-detail-2'),
    status: 'published',
    tags: ['scotch', 'speyside'],
    attributes: [
      { label: 'Xuất xứ', value: 'Speyside, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '40%' },
      { label: 'Tuổi rượu', value: '12 năm' },
      { label: 'Loại thùng', value: 'Bourbon' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-15',
  },
  {
    id: '16',
    nameVN: 'Ardbeg 10 Năm',
    slug: 'ardbeg-10',
    price: 2800000,
    description: 'Một loại Islay single malt cổ điển, cực kỳ đậm vị khói than bùn, i-ốt và một chút vị ngọt của mạch nha.',
    image: getImage('prod-detail-3'),
    status: 'published',
    tags: ['scotch', 'islay'],
    attributes: [
      { label: 'Xuất xứ', value: 'Islay, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '46%' },
      { label: 'Tuổi rượu', value: '10 năm' },
      { label: 'Loại thùng', value: 'Bourbon' },
      { label: 'Lọc lạnh', value: 'Không' }
    ],
    createdAt: '2023-01-16',
  },
  {
    id: '17',
    nameVN: 'Baron de Sigognac 20 Năm',
    slug: 'baron-de-sigognac-20',
    price: 4200000,
    status: 'published',
    description: 'Một loại Bas-Armagnac tinh tế, thể hiện sự phức hợp tuyệt vời của trái cây khô, gia vị và hương gỗ sồi lâu năm.',
    image: getImage('hero-armagnac'),
    tags: ['armagnac'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp' },
      { label: 'Loại', value: 'Armagnac' },
      { label: 'Nồng độ', value: '40%' },
      { label: 'Tuổi rượu', value: '20 năm' },
    ],
    createdAt: '2023-01-17',
  },
  {
    id: '18',
    nameVN: 'Hibiki 21 Year Old',
    slug: 'hibiki-21',
    price: 45000000,
    status: 'published',
    description: 'Một trong những loại blended whisky được trao giải nhiều nhất thế giới. Cực kỳ êm dịu với hương gỗ sồi Mizunara, cam và mật ong.',
    image: getImage('price-category-50'),
    tags: ['world', 'japan', 'old-rare'],
    attributes: [
      { label: 'Xuất xứ', value: 'Nhật Bản' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '43%' },
      { label: 'Tuổi rượu', value: '21 năm' },
      { label: 'Loại thùng', value: 'Mizunara' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-18',
  },
  {
    id: '19',
    nameVN: 'Dalmore King Alexander III',
    slug: 'dalmore-king-alexander-iii',
    price: 9800000,
    status: 'published',
    description: 'Loại single malt duy nhất trên thế giới được ủ trong 6 loại thùng khác nhau, tạo ra một hương vị phức hợp độc đáo.',
    image: getImage('price-category-10'),
    tags: ['scotch', 'highland'],
    attributes: [
      { label: 'Xuất xứ', value: 'Highland, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '40%' },
      { label: 'Loại thùng', value: 'Port' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-19',
  },
  {
    id: '20',
    nameVN: 'Redbreast 12 Year Old Cask Strength',
    slug: 'redbreast-12-cs',
    price: 3900000,
    status: 'published',
    description: 'Một loại Irish pot still whiskey mạnh mẽ, không lọc lạnh, mang đến hương vị đậm đà của trái cây và gia vị.',
    image: getImage('price-category-5'),
    tags: ['world', 'ireland'],
    attributes: [
      { label: 'Xuất xứ', value: 'Ireland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '58.6%' },
      { label: 'Tuổi rượu', value: '12 năm' },
      { label: 'Loại thùng', value: 'Sherry' },
      { label: 'Lọc lạnh', value: 'Không' }
    ],
    createdAt: '2023-01-20',
  },
  {
    id: '21',
    nameVN: 'Talisker 18 Year Old',
    slug: 'talisker-18',
    price: 12500000,
    status: 'published',
    description: 'Một loại single malt tuyệt vời từ đảo Skye, cân bằng giữa vị khói, tiêu và vị ngọt của trái cây.',
    image: getImage('price-category-20'),
    tags: ['scotch', 'islands', 'old-rare'],
    attributes: [
      { label: 'Xuất xứ', value: 'Islands, Scotland' },
      { label: 'Loại', value: 'Whisky' },
      { label: 'Nồng độ', value: '45.8%' },
      { label: 'Tuổi rượu', value: '18 năm' },
      { label: 'Loại thùng', value: 'Bourbon' },
      { label: 'Lọc lạnh', value: 'Có' }
    ],
    createdAt: '2023-01-21',
  },
  {
    id: '22',
    nameVN: 'Minskoye Shampanskoye',
    slug: 'minskoye-shampanskoye',
    price: 240000,
    status: 'published',
    description: 'Một loại vang sủi phổ biến từ Belarus, hoàn hảo cho những dịp ăn mừng và tụ họp.',
    image: getImage('minskoye-shampanskoye'),
    tags: ['wine', 'sparkling'],
    attributes: [
      { label: 'Xuất xứ', value: 'Belarus' },
      { label: 'Loại', value: 'Vang Sủi' },
      { label: 'Nồng độ', value: '12%' },
    ],
    isNew: true,
    createdAt: '2024-07-29',
  },
  {
    id: '23',
    nameVN: 'Vang nổ Nga Zolotoe (Best seller)',
    slug: 'vang-no-nga-zolotoe',
    price: 280000,
    status: 'published',
    description: 'Vang nổ Zolotoe, một sản phẩm bán chạy nhất, sản xuất tại Hungary theo phong cách Nga, mang đến hương vị tươi mát và sảng khoái.',
    image: getImage('zolotoe-wine'),
    tags: ['wine', 'sparkling', 'bestseller'],
    attributes: [
      { label: 'Xuất xứ', value: 'Hungary (Sản xuất theo phong cách Nga)' },
      { label: 'Loại', value: 'Vang Sủi' },
      { label: 'Nồng độ', value: '12%' },
    ],
    isNew: true,
    isFeatured: true,
    createdAt: '2024-07-30',
  },
  {
    id: '24',
    nameVN: 'Chateau La Grace Dieu 2005',
    slug: 'chateau-la-grace-dieu-2005',
    price: 4200000,
    status: 'published',
    description: 'Một chai vang đỏ Pháp từ vùng Saint-Émilion danh tiếng, niên vụ 2005, hứa hẹn một trải nghiệm hương vị phức hợp và tinh tế.',
    image: getImage('chateau-la-grace-dieu-2005'),
    tags: ['wine', 'old-rare'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp – Saint-Émilion' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    isFeatured: true,
    createdAt: '2024-07-31',
  },
  {
    id: '25',
    nameVN: 'Sâm panh Nga Đỏ',
    slug: 'sam-panh-nga-do',
    price: 240000,
    status: 'published',
    description: 'Một loại vang nổ đỏ theo phong cách Nga, sản xuất tại Hungary, mang đến hương vị độc đáo và mới lạ.',
    image: getImage('sampanh-nga-do'),
    tags: ['wine', 'sparkling'],
    attributes: [
        { label: 'Xuất xứ', value: 'Hungary (Phong cách Nga)' },
        { label: 'Loại nho', value: 'Furmint (Sản xuất vang đỏ)' },
        { label: 'Nồng độ cồn', value: '12,5% vol' },
    ],
    isNew: true,
    createdAt: '2024-08-01',
  },
  {
    id: '26',
    nameVN: 'Chateau La Grace Dieu 2010',
    slug: 'chateau-la-grace-dieu-2010',
    price: 3800000,
    status: 'published',
    description: 'Một chai vang đỏ Pháp tuyệt vời từ Saint-Émilion, niên vụ 2010, với hương vị đậm đà và cấu trúc tốt.',
    image: getImage('chateau-la-grace-dieu-2010'),
    tags: ['wine', 'old-rare'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp – Saint-Émilion' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    isFeatured: true,
    createdAt: '2024-08-02',
  },
  {
    id: '27',
    nameVN: 'Chateau La Grace Dieu 2015',
    slug: 'chateau-la-grace-dieu-2015',
    price: 3500000,
    status: 'published',
    description: 'Một chai vang đỏ Pháp tuyệt vời từ Saint-Émilion, niên vụ 2015, với hương vị đậm đà và cấu trúc tốt.',
    image: getImage('chateau-la-grace-dieu-2015'),
    tags: ['wine', 'old-rare'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp – Saint-Émilion' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    isFeatured: true,
    createdAt: '2024-08-03',
  },
  {
    id: '28',
    nameVN: 'Chateau La Grace Dieu 2018',
    slug: 'chateau-la-grace-dieu-2018',
    price: 3800000,
    status: 'published',
    description: 'Một chai vang đỏ Pháp tuyệt vời từ Saint-Émilion, niên vụ 2018, với hương vị đậm đà và cấu trúc tốt.',
    image: getImage('chateau-la-grace-dieu-2018'),
    tags: ['wine', 'old-rare'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp – Saint-Émilion' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    isFeatured: true,
    createdAt: '2024-08-04',
  },
  {
    id: '29',
    nameVN: 'Chateau Ma Seguala (MS.3)',
    slug: 'chateau-ma-seguala-ms3',
    price: 800000,
    status: 'published',
    description: 'Một chai vang đỏ tinh tế từ vùng Roussillon, Pháp, mang đến hương vị đậm đà và đặc trưng.',
    image: getImage('chateau-ma-seguala'),
    tags: ['wine'],
    attributes: [
      { label: 'Xuất xứ', value: 'Roussillon, Pháp' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    createdAt: '2024-08-05',
  },
  {
    id: '30',
    nameVN: 'Chateau Sergant – Pomerol (Nhãn Giấy)',
    slug: 'chateau-sergant-pomerol',
    price: 1350000,
    status: 'published',
    description: 'Một chai vang đỏ thanh lịch từ vùng Pomerol danh tiếng của Pháp, phiên bản nhãn giấy độc đáo.',
    image: getImage('chateau-sergant-pomerol'),
    tags: ['wine'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp – Pomerol' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    createdAt: '2024-08-06',
  },
  {
    id: '31',
    nameVN: 'Chateau Sergant – Pomerol (Nhãn Thiếc)',
    slug: 'chateau-sergant-pomerol-tin',
    price: 1450000,
    status: 'published',
    description: 'Một chai vang đỏ thanh lịch từ vùng Pomerol danh tiếng của Pháp, phiên bản nhãn thiếc sang trọng.',
    image: getImage('chateau-sergant-pomerol-tin'),
    tags: ['wine'],
    attributes: [
      { label: 'Xuất xứ', value: 'Pháp – Pomerol' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    createdAt: '2024-08-07',
  },
  {
    id: '32',
    nameVN: 'Cotes Rocheuses (MS.4)',
    slug: 'cotes-rocheuses-ms4',
    price: 1450000,
    status: 'published',
    description: 'Một chai vang đỏ từ Saint-Émilion, Pháp, mang đến hương vị đậm đà và phức hợp.',
    image: getImage('cotes-rocheuses'),
    tags: ['wine'],
    attributes: [
      { label: 'Xuất xứ', value: 'Saint-Émilion, Pháp' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    createdAt: '2024-08-08',
  },
  {
    id: '33',
    nameVN: 'Cuvee Les Naiades Languedoc',
    slug: 'cuvee-les-naiades-languedoc',
    price: 500000,
    status: 'published',
    description: 'Một chai vang đỏ từ Languedoc, Pháp, mang đến hương vị trái cây và cấu trúc cân bằng.',
    image: getImage('cuvee-les-naiades'),
    tags: ['wine'],
    attributes: [
      { label: 'Xuất xứ', value: 'Languedoc – Pháp' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    createdAt: '2024-08-09',
  },
  {
    id: '34',
    nameVN: 'La Petite Gargotte',
    slug: 'la-petite-gargotte',
    price: 380000,
    status: 'published',
    description: 'Một chai vang đỏ thân thiện, dễ uống từ vùng Languedoc-Roussillon, Pháp.',
    image: getImage('la-petite-gargotte'),
    tags: ['wine'],
    attributes: [
      { label: 'Xuất xứ', value: 'Languedoc–Roussillon – Pháp' },
      { label: 'Loại', value: 'Vang Đỏ' },
      { label: 'Nồng độ', value: '13.5%' },
    ],
    isNew: true,
    createdAt: '2024-08-10',
  },
  {
    id: '35',
    nameVN: "Ballantine's Finest",
    slug: 'ballantines-finest',
    price: 441000,
    status: 'published',
    description: 'Bản có hộp. Phối trộn từ hơn 40 loại Whisky ngũ cốc và mạch nha đơn cất.',
    image: getImage('ballantines-finest'),
    tags: ['scotch', 'blended'],
    attributes: [
      { label: 'Xuất xứ', value: 'Scotland' },
      { label: 'Loại', value: 'Blended Scotch Whisky' },
      { label: 'Nồng độ', value: '40%' },
    ],
    isNew: true,
    createdAt: '2024-08-11',
  }
];

export const sampleCategories: Category[] = [
  { id: '1', name: 'Vang Đỏ', slug: 'vang-do', image: getImage('cotes-rocheuses'), status: 'active' },
  { id: '2', name: 'Vang Trắng', slug: 'vang-trang', image: getImage('cuvee-les-naiades'), status: 'active' },
  { id: '3', name: 'Vang Hồng', slug: 'vang-hong', image: getImage('la-petite-gargotte'), status: 'active' },
  { id: '4', name: 'Vang Sủi', slug: 'vang-sui', image: getImage('minskoye-shampanskoye'), status: 'active' },
  { id: '5', name: 'Vang Tráng Miệng', slug: 'vang-trang-mieng', image: getImage('zolotoe-wine'), status: 'active' },
];

export const sampleBlogPosts: BlogPost[] = [
  {
    id: '1',
    author: 'AnSan',
    title: 'NHÀ CHƯNG CẤT WHISKY LỚN NHẤT THẾ GIỚI',
    slug: 'nha-chung-cat-whisky-lon-nhat-the-gioi',
    excerpt: 'Khám phá những gã khổng lồ đứng sau những chai whisky trứ danh, tìm hiểu về quy mô và sản lượng đáng kinh ngạc của họ.',
    createdAt: new Date('2024-02-14'),
    image: getImage('hero-lakes'),
    categories: ['DISTILLERIES', 'NEWS'],
  },
  {
    id: '2',
    author: 'AnSan',
    title: '5 ĐIỀU BẠN KHÔNG BIẾT VỀ SMWS',
    slug: '5-dieu-ban-khong-biet-ve-smws',
    excerpt: 'The Scotch Malt Whisky Society không chỉ là một hiệp hội, đó là một thế giới riêng. Cùng khám phá 5 bí mật thú vị về tổ chức này.',
    createdAt: new Date('2024-02-04'),
    image: getImage('hero-smws'),
    categories: ['WHISKY BASICS', 'DISTILLERIES'],
  },
  {
    id: '3',
    author: 'AnSan',
    title: '8 ĐIỀU BẠN CHƯA BIẾT VỀ NHÀ CHƯNG CẤT GLENTURRET',
    slug: '8-dieu-ban-chua-biet-ve-glenturret',
    excerpt: 'Đi sâu vào lịch sử và những câu chuyện ít người biết về Glenturret, một trong những nhà chưng cất lâu đời nhất Scotland.',
    createdAt: new Date('2024-03-13'),
    image: getImage('hero-armagnac'),
    categories: ['DISTILLERIES'],
  },
  {
    id: '4',
    author: 'AnSan',
    title: 'ĐÁNH GIÁ CHI TIẾT: THE MACALLAN 18 SHERRY OAK',
    slug: 'review-macallan-18-sherry-oak',
    excerpt: 'Một trong những chai single malt được yêu thích nhất. Liệu The Macallan 18 có xứng đáng với danh tiếng của mình? Cùng AnSan tìm hiểu.',
    createdAt: new Date('2024-04-20'),
    image: getImage('featured-macallan-25'),
    categories: ['WHISKY REVIEW'],
  },
  {
    id: '5',
    author: 'AnSan',
    title: 'SPIRITS LÀ GÌ? PHÂN BIỆT CÁC LOẠI RƯỢU MẠNH CƠ BẢN',
    slug: 'what-is-spirits',
    excerpt: 'Từ Gin, Vodka đến Rum và Tequila, bài viết này sẽ giúp bạn phân biệt và hiểu rõ hơn về thế giới đa dạng của rượu mạnh (spirits).',
    createdAt: new Date('2024-05-01'),
    image: getImage('hero-armagnac'),
    categories: ['SPIRITS', 'WHISKY BASICS'],
  },
  {
    id: '6',
    author: 'AnSan',
    title: 'KHÁM PHÁ HƯƠNG VỊ WHISKY: CÁC BƯỚC NẾM THỬ CHO NGƯỜI MỚI',
    slug: 'whisky-tasting-guide-for-beginners',
    excerpt: 'Học cách nếm thử whisky như một chuyên gia. Hướng dẫn chi tiết từ màu sắc, hương thơm đến hậu vị để bạn có trải nghiệm trọn vẹn nhất.',
    createdAt: new Date('2024-05-15'),
    image: getImage('gift-set-tasting'),
    categories: ['WHISKY BASICS'],
  },
  {
    id: '7',
    author: 'AnSan',
    title: 'SO SÁNH WHISKY: ARDBEG 10 VS LAGAVULIN 16',
    slug: 'review-ardbeg-10-vs-lagavulin-16',
    excerpt: 'Hai gã khổng lồ của vùng Islay, Scotland. Cuộc đối đầu kinh điển giữa hai phong cách khói than bùn khác biệt. Ai sẽ là người chiến thắng?',
    createdAt: new Date('2024-06-01'),
    image: getImage('prod-detail-3'),
    categories: ['WHISKY REVIEW'],
  },
   {
    id: '8',
    author: 'AnSan',
    title: 'THÁI LAN TẠO DẤU MỐC LỊCH SỬ VỚI WHISKY SINGLE MALT ĐẦU TIÊN',
    slug: 'thai-lan-tao-dau-moc-lich-su-voi-whisky-single-malt-dau-tien',
    excerpt: 'PRAKAAN, whisky single malt đầu tiên của Thái Lan, đã chính thức ra mắt toàn cầu, đánh dấu một bước tiến lớn cho ngành công nghiệp rượu mạnh của đất nước này.',
    createdAt: new Date('2025-06-25'),
    image: getImage('hero-lakes'),
    categories: ['NEWS'],
  },
  {
    id: '9',
    author: 'AnSan',
    title: 'LAPHROAIG RA MẮT ARCHIVE COLLECTION 38 NĂM TUỔI',
    slug: 'laphroaig-ra-mat-archive-collection-38-nam-tuoi',
    excerpt: 'Laphroaig vừa công bố phiên bản thứ hai trong dòng Archive Collection – một chai single malt 38 năm tuổi, chưng cất vào năm 1985.',
    createdAt: new Date('2025-06-25'),
    image: getImage('hero-macallan'),
    categories: ['NEWS'],
  },
  {
    id: 'ycTwIHFTbWZe0lGYGJU6',
    author: 'AnSan',
    title: 'RUOU VANG AN SAN',
    slug: 'ruou-vang-an-san',
    excerpt: 'installHook.js:1 Error fetching post or post not found: null overrideMethod @ installHook.js:1 installHook.js:1 Error fetching post or post not found: null overrideMethod @ installHook.js:1 ',
    content: "<p>PLEASE CAREFULLY CHECK YOUR ARTICLE FOR WHY YOU CAN'T CREATE THE ARTICLE DETAILS PAGE EVEN AFTER CREATING THE ARTICLE. CHECK EVERYTHING.</p>",
    createdAt: new Date('2026-01-09T03:53:10.000Z'),
    image: {
      url: "https://firebasestorage.googleapis.com/v0/b/studio-8476793219-f7142.firebasestorage.app/o/blog%2F1c5cbd8d-1c27-41d0-a867-b2844e389fc1-RUOU-CHVAS-18-HOP-QUA-2026%20(1).jpg?alt=media&token=9bb18db1-dcfd-48ab-9d27-28d20111fd4d",
      path: "blog/1c5cbd8d-1c27-41d0-a867-b2844e389fc1-RUOU-CHVAS-18-HOP-QUA-2026 (1).jpg"
    },
    categories: ['NEWS'],
  }
];

export const sampleTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Anh Trần Tuấn',
    title: 'Doanh nhân',
    quote: 'Bộ sưu tập rượu vang ở đây thật sự ấn tượng. Tôi đã tìm thấy những chai vang hiếm mà tôi đã tìm kiếm từ lâu. Dịch vụ tư vấn rất chuyên nghiệp.',
    avatar: getImage('prod-detail-1'),
  },
  {
    id: '2',
    name: 'Chị Minh Anh',
    title: 'Chuyên gia ẩm thực',
    quote: 'Chất lượng rượu vang vượt xa mong đợi của tôi. Mỗi chai vang đều kể một câu chuyện riêng. Chắc chắn tôi sẽ quay lại.',
    avatar: getImage('prod-detail-2'),
  },
  {
    id: '3',
    name: 'Chị Gia Linh',
    title: 'Nhà sưu tập rượu',
    quote: 'Là một nhà sưu tập, tôi đánh giá cao sự đa dạng và chất lượng của các loại rượu vang ở đây. Trang web rất trang nhã và dễ sử dụng.',
    avatar: getImage('prod-detail-3'),
  },
];

    

    

    

    
    
