services:
  ansanweb:
    image: ghcr.io/chung2310/ansanweb:latest
    build: .
    restart: always
    ports:
      - "3006:3006"
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
      PORT: 3006
      HOSTNAME: 0.0.0.0
      INTERNAL_API_URL: http://127.0.0.1:3006/api/v1
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: default_network
    external: true
